modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/The-Acronym-Coders/The Loader/issues"

[[mods]]
    modId="theloader"
    version="${file.jarVersion}"
    displayName="The Loader"
    authors="SkySom"
    description='''
        Loads Data and Resource Packs from the main Minecraft folder
    '''

[[dependencies.theloader]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.68,)"
    ordering="NONE"
    side="BOTH"